#!/usr/bin/env python3
"""Artome OS Core Desktop Environment Daemon - Complete Audio Suite with Barge-In & AT-SPI2 Screen Reader."""

import os
import sys
import subprocess
from faster_whisper import WhisperModel

from earcons import init_earcons, play_earcon
from audio_engine import PiperTTS, DynamicVADListener
from intent_router import ask_artome_ai, ask_ai
from browser_engine import AudioWebBrowser
from mail_engine import AudioMailClient
from ide_engine import AudioIDE
from file_browser_engine import AudioFileBrowser
from doc_writer_engine import AudioDocWriter
from system_settings_engine import AudioSystemSettings
from ebook_engine import AudioEBookReader
from command_navigator import AudioCommandNavigator
from wakeword_engine import WakeWordDetector
from screen_reader import AtspiScreenReader

print("Initializing Artome OS Core Engine...")
init_earcons()

print("Loading Whisper Speech Recognition...")
whisper_model = WhisperModel("tiny.en", device="cpu", compute_type="int8")

tts = PiperTTS()
listener = DynamicVADListener(silence_threshold_ms=750, energy_threshold=0.018)

browser = AudioWebBrowser()
mail_client = AudioMailClient()
ide = AudioIDE()
file_browser = AudioFileBrowser()
doc_writer = AudioDocWriter()
sys_settings = AudioSystemSettings()
ebook_reader = AudioEBookReader()
navigator = AudioCommandNavigator()
wakeword = WakeWordDetector()
screen_reader = AtspiScreenReader()

current_mode = "DESKTOP"

def execute_action(intent, user_speech=""):
    """Execute action payloads generated by the AI Intent Router or Audio Command Navigator."""
    global current_mode
    action = intent.get("action", "speak")
    speech = intent.get("speech", "")
    target = intent.get("target", "")

    low_speech = user_speech.lower() if user_speech else speech.lower()

    # 0. Wake Word Mode Toggle
    if "wake word" in low_speech:
        if "enable" in low_speech or "on" in low_speech:
            msg = wakeword.toggle_wake_word(True)
        elif "disable" in low_speech or "off" in low_speech:
            msg = wakeword.toggle_wake_word(False)
        else:
            msg = wakeword.toggle_wake_word()
        play_earcon("success")
        tts.speak(msg)
        return

    # 1. AT-SPI2 Screen Summary Request Handler (COMMAND:SCREEN_SUMMARY)
    if action == "screen_summary" or "screen" in low_speech or target == "COMMAND:SCREEN_SUMMARY":
        play_earcon("success")
        if speech:
            tts.speak(speech)
        else:
            summary = screen_reader.generate_screen_summary_payload()
            tts.speak(f"Screen summary: {summary[:300]}")
        return

    # 2. Global Audio Help & Command Navigation Prompts
    if any(h_word in low_speech for h_word in ["help", "what can i say", "commands"]):
        play_earcon("success")
        tts.speak(navigator.get_audio_help(current_mode))
        return

    if any(m_word in low_speech for m_word in ["main menu", "menu", "navigation menu", "categories"]):
        play_earcon("success")
        tts.speak(navigator.get_main_menu_audio())
        return

    # Check numerical / menu navigation selections
    new_mode, menu_speech = navigator.select_menu_option(low_speech)
    if new_mode:
        current_mode = new_mode
        play_earcon("success")
        tts.speak(menu_speech)
        return

    if speech:
        tts.speak(speech)

    try:
        target_lower = target.lower() if target else speech.lower()

        # Mode Switching
        if action == "switch_mode" or "switch to" in target_lower:
            if "browser" in target_lower or "web" in target_lower:
                current_mode = "BROWSER"
            elif "email" in target_lower or "mail" in target_lower:
                current_mode = "EMAIL"
            elif "ide" in target_lower or "code" in target_lower:
                current_mode = "IDE"
            elif "file" in target_lower or "folder" in target_lower:
                current_mode = "FILES"
            elif "doc" in target_lower or "writer" in target_lower:
                current_mode = "DOCS"
            elif "book" in target_lower or "ebook" in target_lower:
                current_mode = "EBOOK"
            elif "setting" in target_lower or "status" in target_lower:
                current_mode = "SETTINGS"
            else:
                current_mode = "DESKTOP"

            play_earcon("success")
            tts.speak(navigator.get_audio_help(current_mode))
            return

        # Audio EBook Reader Handlers
        if current_mode == "EBOOK" or action == "ebook_action":
            if "open" in target_lower or "load" in target_lower:
                bname = target.replace("open book", "").replace("open", "").replace("load", "").strip() or "/tmp/sample_book.txt"
                tts.speak(ebook_reader.load_book(bname))
            elif "chapter" in target_lower and any(char.isdigit() for char in target):
                nums = [int(s) for s in target.split() if s.isdigit()]
                if nums:
                    tts.speak(ebook_reader.read_chapter_audio(nums[0]))
            elif "list" in target_lower or "table of contents" in target_lower:
                tts.speak(ebook_reader.list_chapters_audio())
            elif "next" in target_lower:
                tts.speak(ebook_reader.next_chapter_audio())
            elif "previous" in target_lower or "prev" in target_lower:
                tts.speak(ebook_reader.previous_chapter_audio())
            elif "bookmark" in target_lower:
                if "set" in target_lower:
                    tts.speak(ebook_reader.set_bookmark())
                else:
                    tts.speak(ebook_reader.read_bookmark())
            elif "search" in target_lower:
                q = target.replace("search for", "").replace("search", "").strip()
                tts.speak(ebook_reader.search_book_audio(q))
            else:
                tts.speak(ebook_reader.list_chapters_audio())
            play_earcon("success")
            return

        # Audio Document Writer Handlers
        if current_mode == "DOCS" or action == "doc_action":
            if "new" in target_lower or "create" in target_lower:
                doc_title = target.replace("new document", "").replace("new doc", "").replace("create", "").strip() or "Untitled"
                tts.speak(doc_writer.start_new_doc(doc_title))
            elif "heading" in target_lower:
                h_text = target.replace("add heading", "").replace("heading", "").strip()
                tts.speak(doc_writer.add_heading(h_text))
            elif "paragraph" in target_lower or "text" in target_lower:
                p_text = target.replace("add paragraph", "").replace("paragraph", "").replace("text", "").strip()
                tts.speak(doc_writer.add_paragraph(p_text))
            elif "read" in target_lower or "draft" in target_lower:
                tts.speak(doc_writer.read_draft_audio())
            elif "export" in target_lower or "save" in target_lower:
                tts.speak(doc_writer.export_all_formats())
            elif "dropbox" in target_lower or "cloud" in target_lower or "share" in target_lower:
                tts.speak(doc_writer.share_to_dropbox_or_cloud())
            else:
                tts.speak(doc_writer.read_draft_audio())
            play_earcon("success")
            return

        # Audio System Settings & Status Handlers
        if current_mode == "SETTINGS" or action == "setting_action":
            if "status" in target_lower or "battery" in target_lower or "time" in target_lower:
                tts.speak(sys_settings.get_system_status_audio())
            elif "volume up" in target_lower or "louder" in target_lower:
                tts.speak(sys_settings.volume_up())
            elif "volume down" in target_lower or "quieter" in target_lower:
                tts.speak(sys_settings.volume_down())
            elif "timer" in target_lower:
                nums = [int(s) for s in target.split() if s.isdigit()]
                mins = nums[0] if nums else 5
                tts.speak(sys_settings.set_timer(mins, callback_tts=tts))
            else:
                tts.speak(sys_settings.get_system_status_audio())
            play_earcon("success")
            return

        # Audio IDE Mode Handlers
        if current_mode == "IDE" or action == "ide_action":
            if "open" in target_lower or "load" in target_lower:
                filename = target.replace("open code", "").replace("open", "").replace("load", "").strip() or "artome_core.py"
                tts.speak(ide.load_file(filename))
            elif "function" in target_lower or "def" in target_lower:
                func_name = target.replace("read function", "").replace("function", "").strip()
                tts.speak(ide.read_function(func_name))
            elif "line" in target_lower or "lines" in target_lower:
                tts.speak(ide.read_lines(start_line=1, count=10))
            else:
                tts.speak(ide.load_file("artome_core.py"))
            play_earcon("success")
            return

        # Audio File Browser Handlers
        if current_mode == "FILES" or action == "file_action":
            low_user_speech = user_speech.lower() if user_speech else ""
            
            # Robust voice fallback overrides
            if "search" in low_user_speech or "find" in low_user_speech:
                q = low_user_speech.replace("search for", "").replace("search file", "").replace("search", "").replace("find file", "").replace("find", "").strip()
                tts.speak(file_browser.search_files_audio(q))
            elif "duplicate" in low_user_speech or "dups" in low_user_speech:
                tts.speak(file_browser.get_duplicates_audio())
            elif "index" in low_user_speech or "scan" in low_user_speech:
                folder = low_user_speech.replace("index folder", "").replace("index directory", "").replace("index", "").replace("scan folder", "").replace("scan directory", "").replace("scan", "").strip() or file_browser.cwd
                tts.speak(file_browser.index_directory_audio(folder))
            elif "where" in target_lower or "location" in target_lower or "where am i" in low_user_speech:
                tts.speak(file_browser.get_location_audio())
            elif "list" in target_lower or "show" in target_lower or "list" in low_user_speech:
                tts.speak(file_browser.list_contents_audio())
            elif "read" in target_lower or "view" in target_lower or "read file" in low_user_speech:
                fname = target.replace("read file", "").replace("read", "").strip() if target else low_user_speech.replace("read file", "").replace("read", "").strip()
                tts.speak(file_browser.read_file_audio(fname))
            elif "cd" in target_lower or "go to" in target_lower or "enter" in target_lower or any(w in low_user_speech for w in ["go to", "enter", "cd"]):
                folder = target.replace("go to", "").replace("enter", "").replace("cd", "").strip() if target else low_user_speech.replace("go to", "").replace("enter", "").replace("cd", "").strip()
                tts.speak(file_browser.change_dir(folder))
            else:
                tts.speak(file_browser.list_contents_audio())
            play_earcon("success")
            return

        # Audio Browser Handlers
        if current_mode == "BROWSER" or action == "web_navigate":
            if "search" in target_lower or "search" in speech.lower():
                query = target.replace("search for", "").replace("search", "").strip() or speech
                tts.speak(browser.search(query))
            elif target.startswith("http") or "." in target:
                tts.speak(browser.load_url(target))
            elif "heading" in target_lower or "headings" in speech.lower():
                tts.speak(browser.get_headings_audio())
            elif "link" in target_lower or "links" in speech.lower():
                tts.speak(browser.get_links_audio())
            elif "click" in target_lower or "click" in speech.lower():
                nums = [int(s) for s in target.split() if s.isdigit()]
                if nums:
                    tts.speak(browser.click_link_by_index(nums[0]))
            play_earcon("success")
            return

        # Audio Email Handlers
        if current_mode == "EMAIL" or action == "email_action":
            if "check" in target_lower or "inbox" in target_lower:
                tts.speak("Checking email inbox... You have 2 unread emails.")
            elif "read" in target_lower:
                tts.speak(mail_client.read_email_audio(1))
            play_earcon("success")
            return

        # Desktop System Actions
        if action == "open_app" and target:
            subprocess.Popen([target], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            play_earcon("success")
        elif action == "type_text" and target:
            subprocess.run(["xdotool", "type", target])
            play_earcon("success")
        elif action == "press_key" and target:
            subprocess.run(["xdotool", "key", target])
            play_earcon("success")
        elif action == "run_cmd" and target:
            res = subprocess.check_output(target, shell=True, stderr=subprocess.STDOUT, text=True)
            if res.strip():
                tts.speak(res.strip()[:250])
            play_earcon("success")
        elif action == "speak":
            play_earcon("success")
        else:
            play_earcon("success")

    except Exception as e:
        print(f"Execution Error: {e}")
        play_earcon("error")
        tts.speak(f"Action error: {str(e)[:40]}")


def run_artome():
    """Artome OS Main Daemon Loop."""
    play_earcon("success")
    tts.speak("Artome desktop environment ready with TTS barge-in and AT-SPI2 screen reader.")

    fallback_mode = False
    while True:
        try:
            if not fallback_mode:
                try:
                    # Pass tts engine into listener for continuous Barge-In interruption monitoring!
                    audio_data = listener.listen(max_duration_sec=12, tts_engine=tts)
                    if audio_data is None:
                        continue

                    segments, _ = whisper_model.transcribe(audio_data, beam_size=5)
                    raw_user_text = " ".join([seg.text for seg in segments]).strip()
                except Exception as e:
                    print(f"ALSA/Sound device initialization failed: {e}")
                    print("Switching to interactive Console Fallback Mode...")
                    fallback_mode = True
                    continue
            else:
                try:
                    print(f"\n[{current_mode}] Enter command (or 'exit' to quit): ", end="", flush=True)
                    raw_user_text = sys.stdin.readline().strip()
                except KeyboardInterrupt:
                    break
                if not raw_user_text:
                    continue

            if not raw_user_text:
                continue

            # In console fallback mode, bypass wake word checking to allow direct command input
            if fallback_mode:
                active_command = raw_user_text
                is_activated = True
            else:
                is_activated, active_command = wakeword.check_wake_word(raw_user_text)

            if not is_activated:
                continue

            play_earcon("listening")

            if not active_command:
                tts.speak("Yes?")
                continue

            print(f"\n[{current_mode}] COMMAND: {active_command}")

            if any(word in active_command.lower() for word in ["exit", "quit", "shutdown", "stop"]):
                play_earcon("success")
                tts.speak("Shutting down Artome OS. Goodbye.")
                break

            intent = ask_artome_ai(active_command, mode=current_mode)
            print(f"[{current_mode}] INTENT: {intent}")

            execute_action(intent, user_speech=active_command)

        except KeyboardInterrupt:
            play_earcon("error")
            tts.speak("Artome stopped.")
            break
        except Exception as e:
            print(f"Core Loop Error: {e}")
            play_earcon("error")

if __name__ == "__main__":
    run_artome()
